INSERT INTO post_list (post_num, view_count, category, title, nickname, link, main, file, post_date)
VALUES
(1, 100, 'Tech', 'Introduction to SQL', 'Coder123', 'https://youtube.com/sqlvideo', 'In this video, we will learn SQL basics.', 'files/sql_intro.pdf', '2024-07-15'),
(2, 75, 'Food', 'Best Pizza Places in NYC', 'FoodieQueen', NULL, 'Here are my favorite pizza spots in New York City.', NULL, '2024-07-14'),
(3, 50, 'Travel', 'Top Destinations to Visit', 'Globetrotter', 'https://youtube.com/travelvideo', 'Explore these amazing travel destinations around the world.', 'files/travel_destinations.docx', '2024-07-13'),
(4, 120, 'Tech', 'Getting Started with Python', 'PythonEnthusiast', 'https://youtube.com/pythonvideo', 'Learn how to write your first Python program.', 'files/python_getting_started.pdf', '2024-07-12'),
(5, 90, 'Food', 'Authentic Mexican Tacos Recipe', 'TacoLover', 'https://youtube.com/tacovideo', 'Discover the secrets to making delicious tacos at home.', NULL, '2024-07-11'),
(6, 60, 'Fashion', 'Summer Fashion Trends 2024', 'Fashionista', NULL, 'Check out the hottest fashion trends for this summer.', 'files/summer_fashion_trends.docx', '2024-07-10'),
(7, 85, 'Travel', 'Hidden Gems in Europe', 'ExplorerX', 'https://youtube.com/europevideo', 'Explore lesser-known but beautiful places in Europe.', NULL, '2024-07-09'),
(8, 110, 'Tech', 'Machine Learning Basics', 'MLGeek', 'https://youtube.com/mlvideo', 'An introduction to machine learning concepts and algorithms.', 'files/ml_basics.pdf', '2024-07-08'),
(9, 70, 'Food', 'Ultimate Chocolate Cake Recipe', 'ChocoChef', NULL, 'Learn how to bake the most decadent chocolate cake ever.', 'files/chocolate_cake_recipe.docx', '2024-07-07'),
(10, 95, 'Travel', 'Bucket List Destinations', 'Wanderlust', NULL, 'Places you must visit at least once in your lifetime.', 'files/bucket_list_destinations.pdf', '2024-07-06'),
(11, 80, 'Tech', 'Web Development Tools', 'WebDevPro', NULL, 'Essential tools and resources for web developers.', 'files/webdev_tools.docx', '2024-07-05'),
(12, 105, 'Food', 'Healthy Breakfast Ideas', 'FitFoodie', 'https://youtube.com/healthybreakfastvideo', 'Start your day with nutritious and delicious breakfast options.', NULL, '2024-07-04'),
(13, 65, 'Fashion', 'Winter Fashion Essentials', 'WinterStyle', NULL, 'Must-have clothing items for staying stylish in winter.', 'files/winter_fashion_essentials.docx', '2024-07-03'),
(14, 130, 'Tech', 'Cybersecurity Tips for Beginners', 'CyberSec101', NULL, 'Basic tips to protect yourself online and improve cybersecurity.', 'files/cybersecurity_tips.pdf', '2024-07-02'),
(15, 55, 'Food', 'Quick and Easy Dinner Recipes', 'DinnerTime', NULL, 'Delicious recipes that you can whip up in no time for dinner.', 'files/quick_dinner_recipes.docx', '2024-07-01'),
(16, 115, 'Travel', 'Road Trip Essentials', 'RoadTripper', NULL, 'Pack these essentials for a memorable road trip.', 'files/road_trip_essentials.pdf', '2024-06-30'),
(17, 88, 'Tech', 'Introduction to Data Science', 'DataScienceFan', 'https://youtube.com/datasciencevideo', 'Discover the world of data science and its applications.', NULL, '2024-06-29'),
(18, 72, 'Food', 'Vegetarian Recipes for Beginners', 'VeggieChef', NULL, 'Easy and delicious vegetarian dishes for beginners.', 'files/vegetarian_recipes.docx', '2024-06-28'),
(19, 98, 'Fashion', 'Spring Fashion Trends 2024', 'SpringStyle', NULL, 'The latest fashion trends to try out this spring.', 'files/spring_fashion_trends.docx', '2024-06-27'),
(20, 82, 'Tech', 'Cloud Computing Basics', 'CloudGeek', NULL, 'Fundamentals of cloud computing and its benefits.', 'files/cloud_computing_basics.docx', '2024-06-26'),
(21, 102, 'Food', 'Homemade Pasta Recipes', 'PastaLover', NULL, 'Learn how to make fresh and delicious pasta at home.', 'files/homemade_pasta_recipes.docx', '2024-06-25'),
(22, 78, 'Travel', 'Budget Travel Tips', 'BudgetExplorer', NULL, 'Tips for traveling on a budget without compromising on experience.', 'files/budget_travel_tips.docx', '2024-06-24'),
(23, 122, 'Tech', 'Mobile App Development Tools', 'AppDevPro', NULL, 'Tools and frameworks for developing mobile apps efficiently.', 'files/mobile_app_dev_tools.docx', '2024-06-23'),
(24, 68, 'Food', 'Gourmet Burger Recipes', 'BurgerConnoisseur', NULL, 'Indulge in these gourmet burger recipes for burger lovers.', 'files/gourmet_burger_recipes.docx', '2024-06-22'),
(25, 92, 'Fashion', 'Summer Wardrobe Essentials', 'SummerStyle', NULL, 'Must-have clothing items for a stylish summer wardrobe.', 'files/summer_wardrobe_essentials.docx', '2024-06-21'),
(26, 74, 'Tech', 'Artificial Intelligence Overview', 'AIFanatic', 'https://youtube.com/aivideo', 'An overview of artificial intelligence and its impact.', NULL, '2024-06-20'),
(27, 112, 'Food', 'Healthy Smoothie Recipes', 'SmoothieLover', NULL, 'Refreshingly healthy smoothie recipes for any time of the day.', 'files/healthy_smoothie_recipes.docx', '2024-06-19'),
(28, 62, 'Travel', 'Off-the-Beaten-Path Destinations', 'OffbeatTraveler', NULL, 'Explore unique and off-the-beaten-path destinations around the world.', 'files/off_the_beaten_path_destinations.docx', '2024-06-18'),
(29, 108, 'Tech', 'Big Data Analytics', 'BigDataPro', NULL, 'Understanding big data analytics and its applications.', 'files/big_data_analytics.docx', '2024-06-17'),
(30, 58, 'Food', 'Family Dinner Recipes', 'FamilyChef', NULL, 'Delicious recipes that are perfect for family dinners.', 'files/family_dinner_recipes.docx', '2024-06-16');
